/**
 * Mock Proving Backend
 * 
 * A fast, deterministic proving backend for testing that implements the ProvingBackend
 * interface without performing actual cryptographic operations.
 * 
 * Key Features:
 * - Deterministic proof generation from witness hash
 * - Fast execution (< 100ms per proof)
 * - Groth16-format proof bytes (256 bytes: a=64, b=128, c=64)
 * - Configurable proof validity for testing failure paths
 * - No external dependencies (Barretenberg WASM)
 * 
 * **Important**: Mock proofs are NOT cryptographically valid. They match the Groth16
 * format but will be rejected by real verifiers. Use only for testing contract integration
 * with mocked or bypassed verification.
 */

import { createHash } from 'crypto';
import { ProvingBackend } from '../proof';
import type { PreparedWitness } from '../proof';

/**
 * Configuration for the mock proving backend
 */
export interface MockBackendConfig {
  /**
   * Whether to generate valid-looking proofs or invalid proofs.
   * - true: Generate deterministic proof bytes derived from witness
   * - false: Generate invalid proof (all zeros)
   */
  generateValidProofs: boolean;
  
  /**
   * Optional seed for deterministic proof generation.
   * If not provided, only the witness hash is used.
   */
  seed?: string;
  
  /**
   * Optional delay in milliseconds to simulate proof generation time.
   * Useful for testing timeout handling.
   */
  simulateDelay?: number;
}

/**
 * Mock implementation of ProvingBackend for fast, deterministic testing.
 * 
 * Generates Groth16-format proofs (256 bytes) deterministically from witness data
 * without performing actual cryptographic operations.
 * 
 * Requirements: 6.1, 6.2, 6.3
 */
export class MockProvingBackend implements ProvingBackend {
  private config: MockBackendConfig;
  
  /**
   * Creates a new mock proving backend.
   * 
   * @param config Configuration for proof generation behavior
   */
  constructor(config: MockBackendConfig) {
    this.config = config;
  }
  
  /**
   * Generates a deterministic Groth16-format proof from the witness.
   * 
   * The proof is generated by:
   * 1. Hashing the witness to create a deterministic seed
   * 2. Deriving proof components (a, b, c) from the seed
   * 3. Assembling into Groth16 format (256 bytes total)
   * 
   * @param witness The prepared witness for the withdrawal circuit
   * @returns A 256-byte Groth16-format proof
   */
  async generateProof(witness: PreparedWitness): Promise<Uint8Array> {
    // Optionally simulate delay for performance testing
    if (this.config.simulateDelay && this.config.simulateDelay > 0) {
      await this.delay(this.config.simulateDelay);
    }
    
    // Hash witness to create deterministic seed
    const witnessSeed = this.hashWitness(witness);
    
    // Generate deterministic proof bytes
    const proofBytes = this.generateDeterministicProof(witnessSeed);
    
    return proofBytes;
  }
  
  /**
   * Creates a stable hash of the witness for deterministic proof generation.
   * 
   * The hash includes all witness fields in a canonical order to ensure
   * the same witness always produces the same proof.
   * 
   * @param witness The prepared witness
   * @returns SHA-256 hash of the canonical witness representation
   */
  private hashWitness(witness: PreparedWitness): Buffer {
    // Create canonical JSON representation of witness
    // Note: We use a stable stringify to ensure consistent ordering
    const canonical = this.stableStringify({
      nullifier: witness.nullifier,
      secret: witness.secret,
      leaf_index: witness.leaf_index,
      hash_path: witness.hash_path,
      pool_id: witness.pool_id,
      root: witness.root,
      nullifier_hash: witness.nullifier_hash,
      recipient: witness.recipient,
      amount: witness.amount,
      relayer: witness.relayer,
      fee: witness.fee,
      denomination: witness.denomination,
    });
    
    // Combine with optional seed if provided
    const input = this.config.seed
      ? canonical + this.config.seed
      : canonical;
    
    return createHash('sha256').update(input, 'utf8').digest();
  }
  
  /**
   * Generates a deterministic Groth16 proof structure from a seed.
   * 
   * Groth16 proof format (256 bytes total):
   * - a: G1 point (64 bytes) at offset 0
   * - b: G2 point (128 bytes) at offset 64
   * - c: G1 point (64 bytes) at offset 192
   * 
   * @param seed Deterministic seed for proof generation
   * @returns 256-byte proof in Groth16 format
   */
  private generateDeterministicProof(seed: Buffer): Uint8Array {
    const proof = Buffer.alloc(256);
    
    if (this.config.generateValidProofs) {
      // Generate deterministic but valid-looking proof bytes
      // Derive each component from the seed
      const a = this.deriveProofComponent(seed, 'a', 64);
      const b = this.deriveProofComponent(seed, 'b', 128);
      const c = this.deriveProofComponent(seed, 'c', 64);
      
      // Assemble proof: a || b || c
      a.copy(proof, 0);
      b.copy(proof, 64);
      c.copy(proof, 192);
    } else {
      // Generate invalid proof (all zeros)
      // This will fail proof verification
      proof.fill(0);
    }
    
    return new Uint8Array(proof);
  }
  
  /**
   * Derives a deterministic proof component from a seed and label.
   * 
   * Uses iterative hashing to generate the required number of bytes:
   * - Hash(seed || label || iteration)
   * 
   * @param seed Base seed for derivation
   * @param label Component label ('a', 'b', or 'c')
   * @param length Required length in bytes
   * @returns Deterministic bytes for the proof component
   */
  private deriveProofComponent(seed: Buffer, label: string, length: number): Buffer {
    const labelBuffer = Buffer.from(label, 'utf8');
    let output = Buffer.alloc(0);
    let iteration = 0;
    
    // Generate bytes by iterative hashing until we have enough
    while (output.length < length) {
      const iterationBuffer = Buffer.alloc(4);
      iterationBuffer.writeUInt32BE(iteration, 0);
      
      const input = Buffer.concat([seed, labelBuffer, iterationBuffer]);
      const hash = createHash('sha256').update(input).digest();
      output = Buffer.concat([output, hash]);
      iteration++;
    }
    
    // Return exactly the required length
    return output.slice(0, length);
  }
  
  /**
   * Stable JSON stringification that ensures consistent key ordering.
   * 
   * @param obj Object to stringify
   * @returns Canonical JSON string
   */
  private stableStringify(obj: any): string {
    if (obj === null) return 'null';
    if (obj === undefined) return 'undefined';
    if (typeof obj !== 'object') return JSON.stringify(obj);
    
    if (Array.isArray(obj)) {
      const items = obj.map(item => this.stableStringify(item));
      return '[' + items.join(',') + ']';
    }
    
    // Sort keys for stable ordering
    const keys = Object.keys(obj).sort();
    const pairs = keys.map(key => {
      const value = this.stableStringify(obj[key]);
      return JSON.stringify(key) + ':' + value;
    });
    
    return '{' + pairs.join(',') + '}';
  }
  
  /**
   * Delays execution for the specified number of milliseconds.
   * 
   * @param ms Milliseconds to delay
   * @returns Promise that resolves after the delay
   */
  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
