/**
 * Artifact Loading and Validation Utilities
 * 
 * This module provides utilities for loading circuit artifacts from the manifest
 * and validating their integrity. It supports both file-based loading (Node.js)
 * and direct artifact provision.
 * 
 * **Validates: Requirements 7.1, 7.2, 7.3, 7.4**
 * 
 * Key Responsibilities:
 * - Load ACIR bytecode and ABI from circuit artifact files
 * - Validate artifact integrity against manifest hashes (bytecode and ABI)
 * - Convert manifest entries to CircuitArtifacts format
 * - Provide actionable error messages for artifact loading failures
 * - Support lazy initialization of Barretenberg WASM (handled by NoirBackend)
 * 
 * **Verification Key Handling:**
 * The verification key (vkey) is not stored in the artifact JSON files in the
 * current manifest structure. The vkey is generated by Barretenberg during
 * backend initialization and is not required for proof generation. If off-chain
 * verification is needed, the vkey must be provided separately or generated
 * from the circuit artifacts.
 * 
 * **Lazy Barretenberg Initialization:**
 * This module does not handle Barretenberg WASM initialization. That is the
 * responsibility of the NoirBackend class, which initializes Barretenberg
 * lazily when generateProof() is called. See NoirBackend.setBackend() for
 * manual backend initialization.
 * 
 * @module artifacts
 */

import { readFile } from 'fs/promises';
import { join } from 'path';
import type { CircuitArtifacts } from './types';
import type {
  ZkArtifactManifest,
  ZkArtifactManifestCircuit,
  NoirArtifacts,
} from '../../backends/noir';
import { assertManifestMatchesNoirArtifacts } from '../../backends/noir';
import { ConfigurationError } from './types';

/**
 * Options for loading circuit artifacts
 */
export interface LoadArtifactsOptions {
  /** Path to the manifest file */
  manifestPath: string;
  /** Circuit name to load (e.g., "withdraw") */
  circuitName: string;
  /** Base path for artifact files (defaults to manifest directory) */
  artifactsBasePath?: string;
  /** Whether to validate artifact integrity against manifest hashes */
  validateIntegrity?: boolean;
}

/**
 * Result of artifact loading operation
 */
export interface LoadArtifactsResult {
  /** Loaded circuit artifacts */
  artifacts: CircuitArtifacts;
  /** Manifest used for loading */
  manifest: ZkArtifactManifest;
  /** Manifest entry for the loaded circuit */
  manifestEntry: ZkArtifactManifestCircuit;
}

/**
 * Loads circuit artifacts from the manifest
 * 
 * **Validates: Requirement 7.1** - Load circuit artifacts (ACIR, ABI) from manifest
 * **Validates: Requirement 7.2** - Validate artifact integrity against manifest hashes
 * **Validates: Requirement 7.3** - Handle artifact loading errors with actionable messages
 * 
 * This function:
 * 1. Loads and parses the manifest file
 * 2. Finds the circuit entry in the manifest
 * 3. Loads the circuit artifact file (JSON containing bytecode and ABI)
 * 4. Validates artifact integrity against manifest hashes (bytecode_sha256, abi_sha256)
 * 5. Converts to CircuitArtifacts format
 * 
 * **Verification Key (vkey):**
 * The vkey is not included in the artifact JSON files. It is set to an empty
 * buffer as a placeholder. The vkey is generated by Barretenberg during backend
 * initialization and is not required for proof generation. If you need the vkey
 * for off-chain verification, you must:
 * - Generate it from the circuit artifacts using Barretenberg
 * - Provide it separately when creating the NoirBackend
 * 
 * **Lazy Barretenberg Initialization (Requirement 7.4):**
 * This function does not initialize Barretenberg WASM. Barretenberg is initialized
 * lazily by the NoirBackend when generateProof() is first called. To manually
 * initialize Barretenberg, use NoirBackend.setBackend() with a BarretenbergBackend
 * instance.
 * 
 * @param options Loading options
 * @returns Loaded artifacts, manifest, and manifest entry
 * @throws {ConfigurationError} If loading or validation fails with actionable error message
 */
export async function loadArtifactsFromManifest(
  options: LoadArtifactsOptions
): Promise<LoadArtifactsResult> {
  const {
    manifestPath,
    circuitName,
    artifactsBasePath,
    validateIntegrity = true,
  } = options;

  try {
    // Step 1: Load and parse manifest
    const manifestContent = await readFile(manifestPath, 'utf-8');
    const manifest: ZkArtifactManifest = JSON.parse(manifestContent);

    // Step 2: Find circuit entry in manifest
    const manifestEntry = manifest.circuits[circuitName];
    if (!manifestEntry) {
      throw new ConfigurationError(
        `Circuit "${circuitName}" not found in manifest`,
        {
          manifestPath,
          availableCircuits: Object.keys(manifest.circuits),
        }
      );
    }

    // Step 3: Determine artifact file path
    const basePath = artifactsBasePath || join(manifestPath, '..');
    const artifactPath = join(basePath, manifestEntry.path);

    // Step 4: Load artifact file
    const artifactContent = await readFile(artifactPath, 'utf-8');
    const artifactJson = JSON.parse(artifactContent);

    // Step 5: Convert to NoirArtifacts format for validation
    const noirArtifacts: NoirArtifacts = {
      acir: Buffer.from(artifactJson.bytecode, 'base64'),
      bytecode: artifactJson.bytecode,
      vkey: Buffer.alloc(0), // VKey not in artifact JSON, will be loaded separately if needed
      abi: artifactJson.abi,
      name: artifactJson.name || circuitName,
    };

    // Step 6: Validate artifact integrity if requested
    if (validateIntegrity) {
      try {
        assertManifestMatchesNoirArtifacts(
          manifest,
          circuitName,
          noirArtifacts,
          manifestEntry.path
        );
      } catch (error) {
        throw new ConfigurationError(
          `Artifact integrity validation failed for circuit "${circuitName}"`,
          {
            manifestPath,
            artifactPath,
            circuitName,
          },
          error as Error
        );
      }
    }

    // Step 7: Convert to CircuitArtifacts format
    // Note: vkey is not included in artifact JSON files. It is set to an empty
    // buffer as a placeholder. The vkey is generated by Barretenberg during
    // backend initialization and is not required for proof generation.
    const artifacts: CircuitArtifacts = {
      acir: noirArtifacts.acir,
      vkey: noirArtifacts.vkey || Buffer.alloc(0), // Placeholder - vkey not in artifact JSON
      abi: noirArtifacts.abi || {},
      bytecode: noirArtifacts.bytecode,
      name: noirArtifacts.name,
    };

    // Step 8: Validate that required artifacts are present
    validateArtifactsComplete(artifacts, circuitName);

    return {
      artifacts,
      manifest,
      manifestEntry,
    };
  } catch (error) {
    if (error instanceof ConfigurationError) {
      throw error;
    }

    // Wrap other errors in ConfigurationError
    throw new ConfigurationError(
      `Failed to load artifacts from manifest: ${(error as Error).message}`,
      {
        manifestPath,
        circuitName,
        artifactsBasePath,
      },
      error as Error
    );
  }
}

/**
 * Validates that circuit artifacts match the manifest entry
 * 
 * **Validates: Requirement 7.2** - Validate artifact integrity against manifest hashes
 * 
 * This function wraps the NoirBackend's validation logic and provides
 * harness-specific error handling.
 * 
 * @param manifest Manifest to validate against
 * @param circuitName Circuit name to validate
 * @param artifacts Artifacts to validate
 * @throws {ConfigurationError} If validation fails
 */
export function validateArtifactIntegrity(
  manifest: ZkArtifactManifest,
  circuitName: string,
  artifacts: CircuitArtifacts
): void {
  try {
    // Convert CircuitArtifacts to NoirArtifacts format
    const noirArtifacts: NoirArtifacts = {
      acir: artifacts.acir,
      bytecode: artifacts.bytecode,
      vkey: artifacts.vkey,
      abi: artifacts.abi,
      name: artifacts.name,
    };

    // Use NoirBackend's validation logic
    assertManifestMatchesNoirArtifacts(
      manifest,
      circuitName,
      noirArtifacts
    );
  } catch (error) {
    throw new ConfigurationError(
      `Artifact integrity validation failed for circuit "${circuitName}"`,
      {
        circuitName,
        error: (error as Error).message,
      },
      error as Error
    );
  }
}

/**
 * Loads the manifest file
 * 
 * @param manifestPath Path to manifest file
 * @returns Parsed manifest
 * @throws {ConfigurationError} If loading fails
 */
export async function loadManifest(
  manifestPath: string
): Promise<ZkArtifactManifest> {
  try {
    const content = await readFile(manifestPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    throw new ConfigurationError(
      `Failed to load manifest from ${manifestPath}`,
      { manifestPath },
      error as Error
    );
  }
}

/**
 * Gets the circuit entry from the manifest
 * 
 * @param manifest Manifest to search
 * @param circuitName Circuit name to find
 * @returns Manifest entry for the circuit
 * @throws {ConfigurationError} If circuit not found
 */
export function getCircuitEntry(
  manifest: ZkArtifactManifest,
  circuitName: string
): ZkArtifactManifestCircuit {
  const entry = manifest.circuits[circuitName];
  if (!entry) {
    throw new ConfigurationError(
      `Circuit "${circuitName}" not found in manifest`,
      {
        circuitName,
        availableCircuits: Object.keys(manifest.circuits),
      }
    );
  }
  return entry;
}

/**
 * Checks if circuit artifacts are complete for proof generation
 * 
 * **Validates: Requirement 7.3** - Provide actionable error messages
 * 
 * This function checks that the required artifacts (ACIR, ABI) are present
 * and non-empty. The verification key (vkey) is optional for proof generation.
 * 
 * @param artifacts Artifacts to check
 * @param circuitName Circuit name for error messages
 * @throws {ConfigurationError} If required artifacts are missing or invalid
 */
export function validateArtifactsComplete(
  artifacts: CircuitArtifacts,
  circuitName: string
): void {
  if (!artifacts.acir || artifacts.acir.length === 0) {
    throw new ConfigurationError(
      `ACIR bytecode is missing or empty for circuit "${circuitName}"`,
      {
        circuitName,
        actionable: 'Ensure the circuit artifact file contains valid ACIR bytecode. ' +
                   'The artifact may be corrupted or incomplete. Try regenerating the circuit artifacts.',
      }
    );
  }

  if (!artifacts.abi || Object.keys(artifacts.abi).length === 0) {
    throw new ConfigurationError(
      `ABI is missing or empty for circuit "${circuitName}"`,
      {
        circuitName,
        actionable: 'Ensure the circuit artifact file contains a valid ABI. ' +
                   'The artifact may be corrupted or incomplete. Try regenerating the circuit artifacts.',
      }
    );
  }

  // Note: vkey is optional for proof generation. It is generated by Barretenberg
  // during backend initialization. If you need the vkey for off-chain verification,
  // you must generate it separately or provide it when creating the NoirBackend.
}
